version: "3"

networks:
  npm:
    driver: "bridge"

services:
  nginx:
    image: "nginx:1.25.2-alpine-slim"
    container_name: "nginx"
    restart: "always"
    ports:
      - "8080:80"
      - "8081:81"
    working_dir: "/app"
    volumes:
      - "./src:/app"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - npm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

  # mysql57:
  #   image: "mysql:5.7.43-oracle"
  #   container_name: "mysql57"
  #   restart: "always"
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - "MYSQL_ROOT_PASSWORD=jAtcrLRjmrhabHZBlaMxwVJN0pT3LMEf"
  #     - "MYSQL_DATABASE=sg"
  #     - "TZ=Asia/Shanghai"
  #   volumes:
  #     - "./mysql/etc/conf.d:/etc/mysql/conf.d"
  #     - "./mysql/log:/var/log/mysql"
  #     - "./mysql/mysql:/var/lib/mysql"
  #   networks:
  #     - npm
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   command:
  #     - "--default-authentication-plugin=mysql_native_password"
  #     - "--character-set-server=utf8mb4"
  #     - "--collation-server=utf8mb4_bin"
  #     - "--default-time-zone=+8:00"
  #     - "--explicit_defaults_for_timestamp=true"

  mysql:
    image: "mysql:5.6"
    container_name: "mysql"
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=jAtcrLRjmrhabHZBlaMxwVJN0pT3LMEf"
      - "MYSQL_DATABASE=sg"
      - "TZ=Asia/Shanghai"
    volumes:
      - "./mysql/etc/conf.d:/etc/mysql/conf.d"
      - "./mysql/log:/var/log/mysql"
      - "./mysql/mysql:/var/lib/mysql"
    networks:
      - npm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
      - "--default-time-zone=+8:00"
      - "--explicit_defaults_for_timestamp=true"

  # php-fpm82:
  #   image: "php:8.2.9-fpm-alpine"
  #   container_name: "php-fpm82"
  #   restart: "always"
  #   ports:
  #     - "9000:9000"
  #   working_dir: "/app"
  #   volumes:
  #     - "./src:/app"
  #     - "./php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini"
  #   networks:
  #     - npm
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  php-fpm:
    image: "phpdocker/php56-fpm:latest"
    container_name: "php-fpm"
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: "always"
    ports:
      - "9000:9000"
    working_dir: "/app"
    volumes:
      - "./src:/app"
      - "./php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini"
    networks:
      - npm
    extra_hosts:
      - "host.docker.internal:host-gateway"
